import type { Pizza } from '@/types'

export const PIZZAS: Pizza[] = [
  {
    id: 'marguerite',
    slug: 'marguerite',
    nom: 'Marguerite',
    desc: 'Tomate, mozzarella, olives, origan',
    prix: 10,
    categorie: 'tomate',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-coeur.jpg',
  },
  {
    id: 'napolitaine',
    slug: 'napolitaine',
    nom: 'Napolitaine',
    desc: 'Tomate, anchois, olives',
    prix: 10,
    categorie: 'tomate',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-roquette-crue.jpg',
  },
  {
    id: 'jambon-mozza',
    slug: 'jambon-mozza',
    nom: 'Jambon Mozzarella',
    desc: 'Tomate, jambon blanc, mozzarella, olives, origan',
    prix: 11,
    categorie: 'tomate',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-jambon-burrata.jpg',
  },
  {
    id: 'alsacienne',
    slug: 'alsacienne',
    nom: 'Alsacienne',
    desc: 'Crème fraîche, lardons, oignons',
    prix: 12,
    categorie: 'creme',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-jambon-burrata-2.jpg',
  },
  {
    id: 'reine',
    slug: 'reine',
    nom: 'Reine',
    desc: 'Tomate, jambon blanc, champignons, mozzarella, olives, origan',
    prix: 12,
    categorie: 'tomate',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-parma-detail.jpg',
  },
  {
    id: '4-fromages',
    slug: '4-fromages',
    nom: '4 Fromages',
    desc: 'Tomate, emmental, mozzarella, chèvre, roquefort, olives',
    prix: 13,
    categorie: 'tomate',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-4-fromages.jpg',
  },
  {
    id: 'saumon',
    slug: 'saumon',
    nom: 'Saumon',
    desc: 'Crème fraîche, saumon, aneth, mozzarella',
    prix: 13,
    categorie: 'creme',
    disponible: true,
  },
  {
    id: 'andalouse',
    slug: 'andalouse',
    nom: 'Andalouse',
    desc: 'Tomate, poivrons, oignons, chorizo, mozzarella, olives, origan',
    prix: 13,
    categorie: 'tomate',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-fleurs-roquette.jpg',
  },
  {
    id: 'bolognaise',
    slug: 'bolognaise',
    nom: 'Bolognaise',
    desc: 'Tomate, poivrons, oignons, viande hachée, mozzarella, olives, origan',
    prix: 13,
    categorie: 'tomate',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/duo-pizzas-table.jpg',
  },
  {
    id: 'corsica',
    slug: 'corsica',
    nom: 'Corsica',
    desc: 'Tomate, mozzarella, figatelli, brousse, olives, origan',
    prix: 13,
    categorie: 'tomate',
    disponible: true,
  },
  {
    id: 'vegetarienne',
    slug: 'vegetarienne',
    nom: 'Végétarienne',
    desc: 'Tomate, courgettes, poivrons, oignons, champignons, mozzarella, olives, origan',
    prix: 13,
    categorie: 'tomate',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-fleurs-planche.jpg',
  },
  {
    id: 'poulet-curry',
    slug: 'poulet-curry',
    nom: 'Poulet Curry',
    desc: 'Crème fraîche, poulet, oignons, mozzarella, curry',
    prix: 13,
    categorie: 'creme',
    disponible: true,
  },
  {
    id: 'chevre-miel',
    slug: 'chevre-miel',
    nom: 'Chèvre Miel',
    desc: 'Crème fraîche, chèvre, miel, pignons',
    prix: 14,
    categorie: 'creme',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-figue-chevre.jpg',
  },
  {
    id: 'parma',
    slug: 'parma',
    nom: 'Parma',
    desc: 'Tomate, mozzarella, jambon cru, parmesan, roquette, olive, origan, pesto, crème de balsamique',
    prix: 14,
    categorie: 'speciale',
    disponible: true,
    populaire: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-parma.jpg',
  },
  {
    id: 'italienne',
    slug: 'italienne',
    nom: "L'Italienne",
    desc: 'Tomate, mozzarella, salade, mozza di bufala, tomates séchées, pesto, crème de balsamique',
    prix: 14,
    categorie: 'speciale',
    disponible: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-salade-fleurs.jpg',
  },
  {
    id: 'savoyarde',
    slug: 'savoyarde',
    nom: 'Savoyarde',
    desc: 'Crème fraîche, oignons, pommes de terre, reblochon, mozzarella',
    prix: 15,
    categorie: 'creme',
    disponible: true,
  },
  {
    id: 'tartufo',
    slug: 'tartufo',
    nom: 'Tartufo',
    desc: 'Crème fraîche, sauce tartufata noire, mozzarella, jambon blanc, burrata',
    prix: 19,
    categorie: 'speciale',
    disponible: true,
    populaire: true,
    image: '/pizza-lescapade-medias/pizzas/pizza-truffe-burrata.jpg',
  },
]

export const CATEGORIES = {
  tomate: 'Base tomate',
  creme: 'Base crème',
  speciale: 'Spécialités',
} as const
